services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: salary_hero
      MYSQL_ROOT_PASSWORD: hero
      MYSQL_USER: hero
      MYSQL_PASSWORD: hero
    volumes:
      - ./docker/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql

  salary-backend-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development # comment to test production image
    command: ["node", "dist/main"]
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    depends_on:
      - mysql-db
    links:
      - mysql-db
